### PR TITLE
Implement add module via code and fix error messages

### LINKED ISSUE #67: feat(modules): add modules via code only

### LINKED ISSUE #68: bug(UI): fix inconsistent logging and error messages

### PR DESCRIPTION
**Pull request by domoberzin**
The command works in the following manner:
`add -m -c <module code>`

Data fetched from NUSMods API using the [_java.net.http_](https://docs.oracle.com/en/java/javase/12/docs/api/java.net.http/java/net/http/package-summary.html) package.

If the module is not found on NUSMods, it will return the appropriate error message.

Tasks:
- [X] Implement add module via code only
- [X] Reformat add module command to prefix with `-` instead of `\`
- [X] Fix log and error messages to be more appropriate
- [X] Modify code to return an appropriate response, for e.g. doing `add -t` shows a add module command usage example

### CODE REVIEW

**Comment by jontmy** [comment]
> If module is not found on NUSMods, it will return the appropriate error message.

Great work! Not sure why `add -m -c CM1102` doesn't display anything or return any result though. Every other module code I tried worked fine.

**Comment by domoberzin** [comment]
> > If module is not found on NUSMods, it will return the appropriate error message.
> 
> Great work! Not sure why `add -m -c CM1102` doesn't display anything or return any result though. Every other module code I tried worked fine.

Figured it out, CM1102 has a "-" in the title, as its titled `Chemistry - The Central Science`, and the module title only accepts alphanumeric characters, will fix this later on!

**Comment by jontmy** [comment]
> > > If module is not found on NUSMods, it will return the appropriate error message.
> > 
> > 
> > Great work! Not sure why `add -m -c CM1102` doesn't display anything or return any result though. Every other module code I tried worked fine.
> 
> Figured it out, CM1102 has a "-" in the title, as its titled `Chemistry - The Central Science`, and the module title only accepts alphanumeric characters, will fix this later on!

what an odd edge case lmao

**Comment by domoberzin** [comment]
> > > > If module is not found on NUSMods, it will return the appropriate error message.
> > > 
> > > 
> > > Great work! Not sure why `add -m -c CM1102` doesn't display anything or return any result though. Every other module code I tried worked fine.
> > 
> > 
> > Figured it out, CM1102 has a "-" in the title, as its titled `Chemistry - The Central Science`, and the module title only accepts alphanumeric characters, will fix this later on!
> 
> what an odd edge case lmao

Nice job finding the bug! 
Fixed it by removing all the non-alphanumeric characters for now, so some modules for e.g CM1102 will show up as
`Chemistry The Central Science`, may not be the best or most accurate representation, but we can discuss other ways to do it in the future. Changing the validity check during creation of the module name requires quite a few changes, especially in the storage component when reading from the saved JSON file.

**Comment by jontmy** [comment]
Works as expected with the fix!

Found one more thing, not sure whether it's a bug - should `add -c <mod code>` without `-m` add the module?:

- if the module code isn't valid, it shows "Module code does not exist", but "Invalid command" is logged
- If the module code is valid, it adds the module

**Comment by domoberzin** [comment]
Had to reformat the AddCommandParser, combining all instances of `add` to redirect to one parser makes it very messy and long, also makes it more tedious to return the correct error message. 

Fixed this via segragating which parser is called in TaskBookParser by nesting a second conditional to check the arguments for the presence of `-t` or `-m`. After this, the error messages in the event of incorrect inputs is more consistent with what the user entered.

Could definitely modify it to make it more OOP-ish but I think we should create another issue for that along with refactoring the usages of Person and AddressBook.

**Review by jontmy — APPROVED** [review]
lgtm!

**Pull request merged**
