### PR TITLE
Implement `prioritize` command

### LINKED ISSUE #82: feat(tasks): Assign priority ratings to tasks
# User Story

Tasks/Deadlines User Story 4

As a student overwhelmed by tasks, I can assign priority ratings to various tasks, so that I can prioritize the ones that I deem to be more important.

## Notes
Priority ratings should fall in `LOW, MEDIUM, HIGH`

### LINKED ISSUE #83: feat(tasks): Sort tasks via priority rating
# User Story

Tasks/Deadline User Story 5

As a student overwhelmed by tasks, I can sort tasks according to their priority ratings, so that I know which ones to work on first.

## Notes
Sort low to high or high to low

### PR DESCRIPTION
**Pull request by jontmy**
Resolves #82 and #83.

### CODE REVIEW

**Comment by jontmy** [comment]
**Prioritizing**

https://user-images.githubusercontent.com/50949210/196951894-5cce1f00-b908-4571-93be-2926e029739c.mov

**Comment by jontmy** [comment]
**Integration with un/archiving**

https://user-images.githubusercontent.com/50949210/196952717-fcfc6d49-0b3f-4758-844e-a64f6678c3fd.mov

**Comment by jontmy** [comment]
Notice that tasks are sorted by non-archived first, then highest priority first, then lexicographically.

**Review by HoJunHao2000 — APPROVED** [review]
LGTM!

**Pull request merged**
